### ISSUE TITLE
Export a specific member group fails

### ISSUE THREAD

**Issue by neckarpixel** [markocupic/export_table#10]
Hey, 
I want to export all members of a specific group, but the SQL filter
`[["tl_member.groups =?"],["3"]]`
ist not working.
Any idea?

**Comment by markocupic** [comment]
You could try `[["tl_member.groups LIKE '%:1;%' AND id >?"],["0"]]`

Contao stores member groups as serialized array in the db. That means ´array(1,2)´ becomes ´a:2:{i:0;i:1;i:1;i:2;}´

**Comment by neckarpixel** [comment]
Thank you for the tipp. One litte change was necassary:
`[["tl_member.groups LIKE '%:\"3\";%' AND id > ?"],["0"]]`

The ID of the group is surrounded by "".

**Comment by markocupic** [comment]
Yes, this might be, because the ids are stored in an array of strings.
