### ISSUE TITLE
Kleine Fehler in export_table

### ISSUE THREAD

**Issue by srothe** [markocupic/export_table#13]
Hi Marco,
ich habe gerade dein export_table-Modul unter contao 4.13.6 getestet.
Zwei Punkte sind mir aufgefallen:
* die Tabelle wird in der Liste der gespeicherten Export nicht angezeigt
* scheinbar werden zusätzliche Spalten, die in diesem Fall per contao/dca/tl_member.php hinzugefügt wurden, beim Export nur als leere Spalte ausgegeben (oder muss dafür in der DCA Def. etwas angepasst werden)
Vielen Dank und Beste Grüße 
sven

PS:
Ich weiß, wir haben noch ein Thema offen und ich bin in der Pflicht - ich habe mir heute endlich mal eine Testumgebung mit contao 4.13 aufgesetzt und werde mir in den nächsten Tagen die Event-Warteliste v6.0-beta2 ansehen.

**Comment by markocupic** [comment]
Ich kann deinen Fehler nicht reproduzieren.
Welche Version export_table Version ist genau installiert? 
Welche PHP Version?

**Comment by srothe** [comment]
Hi Marko,
contao 4.13.6
export table Version 5.3.12
PHP Version 7.4.30

Beim Versuch auf die aktuelle Version von export_table zu wechseln, scheitert er erstmal an PHP 7.
Ist das die Ursache?

Beste Grüße
sven


***@***.***



Beste Grüße

sven


Von: Marko Cupic ***@***.***>
Datum: Freitag, 19. August 2022 um 08:48
An: markocupic/export_table ***@***.***>
Cc: srothe ***@***.***>, Author ***@***.***>
Betreff: Re: [markocupic/export_table] Kleine Fehler in export_table (Issue #13)

Ich kann deinen Fehler nicht reproduzieren.
Welche Version export_table Version ist genau installiert?
Welche PHP Version?

**Comment by markocupic** [comment]
> Beim Versuch auf die aktuelle Version von export_table zu wechseln, scheitert er erstmal an PHP 7.

Ja, die 5.4.* Versionen sind ab[ PHP 8.1](https://github.com/markocupic/export_table/blob/82bdfd6b2cb3b2cbf59e6b4c38a2a3e313733f78/composer.json#L25) freigegeben
