### ISSUE TITLE
keine Auflösung der Inserttags

### ISSUE THREAD

**Issue by zonky2** [markocupic/export_table#15]
V 5.3.12

in https://github.com/markocupic/export_table/blob/b682c7155218affc073b22f2753fe5fb76e897b8/src/Export/ExportTable.php#L136

die Inserttags werden "entfernt"

z.B.

```
[["mm_anmeldungen.member_id=?"],["{{user::id}}"]]
```

**Comment by markocupic** [comment]
Entfernt und mit der user id des Backend Users ersetzt? Das wäre ja gewollt.

**Comment by zonky2** [comment]
leider nein - das Ergebnis sieht dann so aus

```[["mm_anmeldungen.member_id=?"],[""]]```

wenn man statt dem Inserttag fest eine ID einträgt in den Einstellungen, gehts...

**Comment by markocupic** [comment]
Das Inserttag User bezieht sich auf den angemeldeten FE User. Habe es oben falsch geschrieben. Lässt du den Export im Frontend Scope laufen? Sprich über einen Link?

**Comment by zonky2** [comment]
> Das Inserttag `user` bezieht sich auf den angemeldeten FE User. 

das ist schon klar ;-)

ja, über einen Link im FE bei angemeldetem User

**Comment by zonky2** [comment]
hab nochmal ein Update gemacht und nun gehts ... hmm??

```
"[["mm_anmeldungen.member_id=?"],["{{user::id}}"]]"
=>
"[["mm_anmeldungen.member_id=?"],["4"]]"

```

**Comment by zonky2** [comment]
Fehler gefunden: jemand hatte bei der URL des Links was geändert... sorry
