### ISSUE TITLE
Laden von $controllerAdapter in function run ist nicht notwendig

### ISSUE THREAD

**Issue by SimonSpi** [markocupic/export_table#17]
Ich habe das Modul etwas missbraucht und mir über einen händischen Datenbankeintrag einen Export aus zwei Tabellen gebaut. Dabei ist mir aufgefallen, dass in src/export/exportTable.php in der function run die Variable $controllerAdapter vermutlich unnötig ist. Aufgefallen ist dies, weil mit dem händischen Export aus zwei Tabellen bei $controllerAdapter->loadDataContainer($strTable, true); (Zeile 62) eine Exception geworfen wird.

Im Allgemeinen ist das Modul super praktisch, danke dafür!

**Comment by markocupic** [comment]
Der Adapter ist nicht unnötig, er wird gebraucht, um die DCA zu laden. 
Was steht denn in deiner Exception genau geschrieben?

**Comment by SimonSpi** [comment]
Hallo Marko

Sorry, dann habe ich das zu wenig genau angeschaut. Interessanterweise funktioniert der Export wenn ich die Zeile 62 auskommentiere. 
Die Exception ist "Invalid language file name "tl_calendar_events, tl_calendar_events_member"". Ich nehme an, dass dies passiert, weil bei mir nun zwei Tabellen in $strTable stehen und deshalb das Language File nicht gefunden werden kann. Wie gesagt habe ich das Modul ja missbraucht von daher kann das Ticket geschlossen werden.

Beste Grüsse
