### ISSUE TITLE
Allow Insert-Tags in SQL-Filter

### ISSUE THREAD

**Issue by SGehle** [markocupic/export_table#2]
ExportTable.php:103
`            'arrFilter'           => $filterExpression != '' ? json_decode(\Controller::replaceInsertTags($filterExpression)) : array(),
`

**Comment by SGehle** [comment]
`            'arrFilter'           => $filterExpression != '' ? json_decode(\Controller::replaceInsertTags($filterExpression)) : array(),
`

**Comment by markocupic** [comment]
Spannend. Was ist der Anwendungsfall? Wenn ich fragen darf.

**Comment by SGehle** [comment]
Natürlich. Ich Filtere den Export einer Tabelle nach Datensätzen die bestimmten Frontend-Nutzern zugeordnet sind. Mit {{user::id}} kann ich dies sehr einfach realisieren.

**Comment by markocupic** [comment]
Added in https://github.com/markocupic/export_table/commit/abb1c8fcff64a551ab29b1031d3fc6aa16c68e08

**Comment by markocupic** [comment]
@SGehle 
Würdest du das mal testen? Version 3.1.0
Lg M
