### ISSUE TITLE
Controller not returning a Response object

### ISSUE THREAD

**Issue by SamesOfAm** [markocupic/export_table#20]
Hello, 

I am getting the following error when trying to use the Deep-Link feature and the checkbox "Save export in Contao file system".
The regular click on the black download icon works fine.

`request.CRITICAL: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\ControllerDoesNotReturnResponseException: "The controller must return a "Symfony\Component\HttpFoundation\Response" object but it returned null. Did you forget to add a return statement somewhere in your controller?" at /kunden/94126_07745/rp-hosting/700190/800341/contao/vendor/markocupic/export_table/src/Controller/DownloadController.php line 46 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\ControllerDoesNotReturnResponseException(code: 0): The controller must return a \"Symfony\\Component\\HttpFoundation\\Response\" object but it returned null. Did you forget to add a return statement somewhere in your controller? at /kunden/94126_07745/rp-hosting/700190/800341/contao/vendor/markocupic/export_table/src/Controller/DownloadController.php:46)"} []`

Maybe the Deep-Link feature was not intended to work with the saving in file system feature, but in that case I would expect some sort of warning or disabled checkboxes.

Thank you so much for developing this great extension, I really appreciate it.

Looking forward to any help or hints.

Have a good one

**Comment by markocupic** [comment]
pull requests welcome ;-)

**Comment by SamesOfAm** [comment]
Thanks for the reply, sadly I am not a PHP developer and can't contribute. Maybe someone else can help. Thanks to everyone considering it!

**Comment by SamesOfAm** [comment]
Thanks so much for the quick fix!
