### ISSUE TITLE
SQL-Filter wir ignoriert

### ISSUE THREAD

**Issue by SFachinger** [markocupic/export_table#4]
C4.9.1 
export_table 3.2.2

Der SQL-Filter:
`[["booking_id=?","2020-01"]]`
wird ignoriert.
Geht noch in der 3.1.2

MfG Steffen

**Comment by markocupic** [comment]
Schaue es mir heute Abend an. 
Lg m

**Comment by SFachinger** [comment]
OK, wollte es nur melden.


Hab wieder die 3.1.2  im Einsatz




On Fri, Apr 3, 2020 at 2:33 PM +0200, "Marko Cupic" <notifications@github.com> wrote:















Schaue es mir heute Abend an.

Lg m

**Comment by markocupic** [comment]
Fixed in version 3.2.3

**Comment by SFachinger** [comment]
Thy, teste es morgen




Steffen




On Fri, Apr 3, 2020 at 7:56 PM +0200, "Marko Cupic" <notifications@github.com> wrote:















Fixed in version 3.2.3

**Comment by SFachinger** [comment]
In der aktullen Version 3.3.x tritt der gleiche Fehler wieder auf...

MfG Steffen

**Comment by markocupic** [comment]
Probier den Filter mal so zu setzen:
[["booking_id=?"],["2020-01"]]

Lg Marko

![image](https://user-images.githubusercontent.com/1525166/85198623-61230d80-b2ea-11ea-9603-6f99f99a29f6.png)

**Comment by SFachinger** [comment]
Sorry, das war anschinend mein Fehler.
Die geänderte Schreibweise mit [["tl_seminaranmeldungen.booking_id=?"],["2020-01"]] hatte ich probiert, brachte aber keine Änderung bei der Abfrage.
Jetzt funktioniert es plötzlich. 

Trotzdem vielen Dank

LG Steffen
