### ISSUE TITLE
Unable to add new export 

### ISSUE THREAD

**Issue by w3scout** [markocupic/export_table#6]
When i try to add a new export configuration, I get this error message (C4.9.21, MariaDB 10.3):

"An exception occurred while executing 'SHOW FULL COLUMNS FROM': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1"

**Comment by w3scout** [comment]
Hej Marko,
it´s the current version (4.0.4).
Yes, I´ve tried a database update, but the install tool didn´t show anything. 
Pozdrav!

**Comment by markocupic** [comment]
Please update the extension and run the install tool. I've added some fields to the "tl_export_table" table
